[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#000005"
foreground = "#F9F9F9"

[font]
size = 9.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[scrolling]
history = 50000

[window]
decorations = "Full"
opacity = 0.9

[window.dimensions]
columns = 130
lines = 55

[window.position]
x = 1940
y = 30
